// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDN2pdK3Lk9posr9t0jeHt2hhH6qrM0JA',
    appId: '1:571695904128:web:a7aa214e934f51e8c87d65',
    messagingSenderId: '571695904128',
    projectId: 'finalyearproject-7b5bb',
    authDomain: 'finalyearproject-7b5bb.firebaseapp.com',
    storageBucket: 'finalyearproject-7b5bb.firebasestorage.app',
    measurementId: 'G-2WP5TNY6SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrI90BDZ713g6L_WCOK0u5Az0nYKrFZRY',
    appId: '1:571695904128:android:c9585123db13982fc87d65',
    messagingSenderId: '571695904128',
    projectId: 'finalyearproject-7b5bb',
    storageBucket: 'finalyearproject-7b5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOVJEh_MIBd56upUoASxfru2fPhNhFBs',
    appId: '1:571695904128:ios:458bdb61cb16157dc87d65',
    messagingSenderId: '571695904128',
    projectId: 'finalyearproject-7b5bb',
    storageBucket: 'finalyearproject-7b5bb.firebasestorage.app',
    iosBundleId: 'com.lostitemtracker.lostItemTrackerClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOVJEh_MIBd56upUoASxfru2fPhNhFBs',
    appId: '1:571695904128:ios:458bdb61cb16157dc87d65',
    messagingSenderId: '571695904128',
    projectId: 'finalyearproject-7b5bb',
    storageBucket: 'finalyearproject-7b5bb.firebasestorage.app',
    iosBundleId: 'com.lostitemtracker.lostItemTrackerClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDN2pdK3Lk9posr9t0jeHt2hhH6qrM0JA',
    appId: '1:571695904128:web:6b4671f6442b46d7c87d65',
    messagingSenderId: '571695904128',
    projectId: 'finalyearproject-7b5bb',
    authDomain: 'finalyearproject-7b5bb.firebaseapp.com',
    storageBucket: 'finalyearproject-7b5bb.firebasestorage.app',
    measurementId: 'G-VK24VVFKHM',
  );

}